[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/TriMinder.apk"
  [headers.values]
    Content-Type = "application/vnd.android.package-archive"
    Content-Disposition = "attachment; filename=\"TriMinder.apk\""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

